fix linting workflow

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -21,22 +21,8 @@ jobs:
         with:
           fetch-depth: 0
 
-      - name: Install Helm
-        uses: Azure/setup-helm@v1
-        with:
-          version: v3.5.2
-
-      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
-      # yamllint (https://github.com/adrienverge/yamllint) which require Python
-      - uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-
-      - name: Install chart-testing
-        uses: helm/chart-testing-action@v2.1.0
-
       - name: Chart linting
-        run: ct lint --config .github/ct-config.yaml
+        run: make lint
 
   docs:
     name: Validate documentation
@@ -49,16 +35,14 @@ jobs:
           fetch-depth: 1
 
       - name: Render documentation
-        run: |
-          docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) \
-            jnorwood/helm-docs:v1.11.0 --sort-values-order file --chart-search-root charts/
+        run: make docs
 
       - name: Check git diff
         run: |
           git update-index -q --ignore-submodules --refresh
           if ! git diff-files --quiet --ignore-submodules -- ; then
             git diff --raw
-            echo '::error:: Generating documentation caused a change. run "docker run --rm --volume "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:v1.11.0 --sort-values-order file --chart-search-root charts/"' && exit 1
+            echo '::error:: Generating documentation caused a change. Run "make docs"' && exit 1
           fi
 
   audit:
@@ -74,7 +58,7 @@ jobs:
       - name: Install Helm
         uses: Azure/setup-helm@v1
         with:
-          version: v3.5.2
+          version: v3.9.0
 
       - name: Setup polaris
         uses: fairwindsops/polaris/.github/actions/setup-polaris@master
